project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "! purcprod/"
    - "! whiting/"
    - "! PerformanceMetrics/"

website:
  title: "FISHEyE"
  search: FALSE
  navbar:
    logo: "images/NOAA_FISHERIES_logoH.png"
    logo-alt: "NOAA Fisheries logo"
    pinned: FALSE
    right:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: literature.qmd
        text: "Literature"
      - href: resources.qmd
        text: "Resources"
      - text: "Contact"
        menu:
          - text: "nwfsc.edc@noaa.gov"
            icon: envelope-fill
            href: "mailto:nwfsc.edc@noaa.gov?subject=FISHEyE"
  page-footer:
    left:
      - href: https://www.fisheries.noaa.gov/region/west-coast/northwest-science
        text: "NWFSC"
      - text: "|"
      - href: https://www.fisheries.noaa.gov/
        text: 'NOAA Fisheries'
      - text: "|"
      - href: https://www.noaa.gov/
        text: "NOAA"
      - text: "|"
      - href: https://www.fisheries.noaa.gov/about-us/privacy-policy
        text: "NOAA privacy policy"
    right:
      - "&copy; NOAA Fisheries 2025"

format:
  html:
    self-contained: true
    anchor-sections: FALSE
    link-external-newwindow: true
    theme:
      - cosmo
      - styles.scss
    fontsize: 1.1em
    mainfont: Montserrat
    google-fonts:
      - Montserrat
    toc: FALSE



